
content: 
  - name: posts
    label: Blog Posts
    path: astro-app/src/content/post
    type: collection
    view: 
      fields: [ title, description, draft, publishDate ]
      primary: title
      sort: [date, title]
      default: 
        search: ''
        sort: publishDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: publishDate
        label: Publish Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
      - name: tags
        label: Tags
        type: string
        list: 
          min: 1
          max: 5
          default: [news]
      - name: coverImage
        label: Cover Image
        type: object
        fields:
        - name: alt
          label: Alt Text
          type: text
        - name: src
          label: Image File
          type: image
          options:
            extensions: [jpg, png]
      - name: ogImage
        label: Social Media Share image
        type: image
        options:
          extensions: [jpg, png]
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
media: astro-app/public/images
